apiVersion: apps/v1
kind: Deployment
metadata:
  name: blobreader-oneshot
spec:
  selector:
    matchLabels:
      app: blobreader-oneshot
  template:
    metadata:
      labels:
        app: blobreader-oneshot
    spec:
      containers:
        - name: blobreader
          image: trulivek8sacreun001.azurecr.io/blobreader/truservice-oneshot:v3
          envFrom: # envFrom loads multiple variables
            - configMapRef: # from a ConfigMap
                name: truservicelog-config-env-file
      imagePullSecrets:
        - name: acr-secret
